### ISSUE TITLE
[usavian] Call for contributors & co-conspirators

### ISSUE THREAD

**Issue by trashbirdecology** [TrashBirdEcology/USAvian#1]
Wanna help? Cool!

Drop me a line here (or via [email](mailto:jburnett@usgs.gov)).

Looking for folks interested in helping paint a clear(er) picture of bird conservation in the US and ideally those to help with contributions in the following areas:
- Data collection
- UX/UI (esp. using maps)
- Database design 
- Database maintenance
- Designing mechanisms for soliciting and fielding feedback

**Comment by trashbirdecology** [comment]
### Confirmed collaborators
Co-conspirator # 1: @krburgio, Cary Institute for Ecosystem Studies
Co-conspirator # 2: @aurielfournier, Forbes Biostation


### Potential collaborators
- Potential for social science in bird cons: [Amy Dayer](https://dayer.fishwild.vt.edu/dayer-2/)
- Potential for social science in bird cons: Ashley [Gramza](https://scholar.google.com/citations?user=949QLjgAAAAJ&hl=en)
- Mapping and visualizations: [Sadie Ryan, UF](http://www.sadieryan.net/)
- PAD-US: [Julie Prior-Magee](https://www.usgs.gov/staff-profiles/julie-prior-magee)
- Someone from Point Blue (and AKN)

**Comment by aurielfournier** [comment]
Waves count me in  👋 

I can do some mapping, and some shiny dev. I'm not great on databases, but can help with data collection, and love a good visualization problem.

**Comment by TrashBirdEcology** [comment]
> Waves count me in

@aurielfournier  have you ever done any mouseover shiny stuff?

**Comment by aurielfournier** [comment]
I have!

There is not one on the website (unless it was added very recently), but I do have that shapefile.

**Comment by Dyounglecturer** [comment]
I would have loved to join your team in field research but I am a Nigerian. The distance is a barrier

**Comment by trashbirdecology** [comment]
> I would have loved to join your team in field research but I am a Nigerian. The distance is a barrier

@Dyounglecturer we have not any field research, and everything is being conducted over the internet. You're welcome to join us in our efforts, but for now the focus will be on USA bird conservation network. If that interests you, feel free to ping us and join in :)

**Comment by trashbirdecology** [comment]
Closing Issue but certainly still open to contributions.
